<style>
table td {border: 1px solid gray; padding: 3px; font-size: 13px;}
form input[type=text] {border: 0px; font: bold 13px ;}
.mytextarea  { width: 100%; border: 0px; font: bold 13px; height: 120px;}
</style>

<form method="post" action="">
<table width="75%">
<tr>
	<td>Generated by<br /><input type="text" value="Mike Georgeson" /></td>
	<td>Date<br /><input type="text" value="10/10/2011" /></td>
</tr>
<tr>
	<td>Project ID<br /><input type="text" value="123-456-789" /></td>
	<td>Project Title<br /><input type="text" value="Spiffing new Project" /></td>
</tr>
<tr>
	<td>Issue<br /><input type="text" value="1.4.6" /></td>
	<td>Project Lead<br /><input type="text" value="Matt Galley" /></td>
</tr>
</table><br /><br />


<table width="75%">
<tr>
	<td>Issue Description<br /><textarea class="mytextarea">Blah de blah de blah de blah de blah de blah de blah de blah de blah</textarea></td>
</tr>
<tr>
	<td>Special Issue Instructions<br /><textarea class="mytextarea">Blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah de blah</textarea></td>
</tr>
</table><br /><br />

<table width="75%">
<tr>
	<td rowspan="2">Doc Title</td>
	<td rowspan="2">Doc #</td>
	<td rowspan="2">Revision </td>
	<td rowspan="2">Issued To</td>
	<td colspan="4" style="text-align: center;">Document Actions</td>

</tr>
<tr>
	
	
	<td>Word</td>
	<td>PDF</td>
	<td>Disc</td>
	<td></td>
</tr>

<?php
/*  
Loop through results and assign a variable to each row
$i = 1;
*/
?>
<tr>
	<td>Issued</td>
	<td>123456</td>
	<td>A</td>
	<td>Steve</td>
	<td><input type="checkbox" id="<?php echo $i;?>word" name="word" checked /></td>
	<td><input type="checkbox" id="<?php echo $i;?>pdf" name="pdf" checked /></td>
	<td><input type="checkbox" id="<?php echo $i;?>disc" name="disc"/></td>
	<td></td>
</tr>

<?php
/*
$i = $i+1;


$maxno = $i;

So you pass to save page the max number of rows and you can then loop through form elements from 1 to $maxno

*/
?>

</table>

<input type="submit" value="Save Form" />
</form>